/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ShellPerfilRouteImport } from './routes/_shell/perfil'
import { Route as ShellNotificacionesRouteImport } from './routes/_shell/notificaciones'
import { Route as ShellCronogramaRouteImport } from './routes/_shell/cronograma'
import { Route as ShellStudentIndexRouteImport } from './routes/_shell/student/index'
import { Route as ShellProyectosIndexRouteImport } from './routes/_shell/proyectos/index'
import { Route as ShellDocenteIndexRouteImport } from './routes/_shell/docente/index'
import { Route as ShellAdminIndexRouteImport } from './routes/_shell/admin/index'
import { Route as ShellRevisionVersionIdRouteImport } from './routes/_shell/revision/$versionId'
import { Route as ShellProyectosProyectoIdRouteImport } from './routes/_shell/proyectos/$proyectoId'
import { Route as ShellAdminUsuariosRouteImport } from './routes/_shell/admin/usuarios'
import { Route as ShellAdminReportesRouteImport } from './routes/_shell/admin/reportes'
import { Route as ShellAdminMateriasIndexRouteImport } from './routes/_shell/admin/materias/index'
import { Route as ShellAdminUsuariosUsuarioIdRouteImport } from './routes/_shell/admin/usuarios_.$usuarioId'
import { Route as ShellAdminMateriasMateriaIdRouteImport } from './routes/_shell/admin/materias/$materiaId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellPerfilRoute = ShellPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificacionesRoute = ShellNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCronogramaRoute = ShellCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentIndexRoute = ShellStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProyectosIndexRoute = ShellProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocenteIndexRoute = ShellDocenteIndexRouteImport.update({
  id: '/docente/',
  path: '/docente/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminIndexRoute = ShellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRevisionVersionIdRoute = ShellRevisionVersionIdRouteImport.update({
  id: '/revision/$versionId',
  path: '/revision/$versionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProyectosProyectoIdRoute =
  ShellProyectosProyectoIdRouteImport.update({
    id: '/proyectos/$proyectoId',
    path: '/proyectos/$proyectoId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAdminUsuariosRoute = ShellAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminReportesRoute = ShellAdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminMateriasIndexRoute = ShellAdminMateriasIndexRouteImport.update({
  id: '/admin/materias/',
  path: '/admin/materias/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminUsuariosUsuarioIdRoute =
  ShellAdminUsuariosUsuarioIdRouteImport.update({
    id: '/admin/usuarios_/$usuarioId',
    path: '/admin/usuarios/$usuarioId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAdminMateriasMateriaIdRoute =
  ShellAdminMateriasMateriaIdRouteImport.update({
    id: '/admin/materias/$materiaId',
    path: '/admin/materias/$materiaId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma': typeof ShellCronogramaRoute
  '/notificaciones': typeof ShellNotificacionesRoute
  '/perfil': typeof ShellPerfilRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/reportes': typeof ShellAdminReportesRoute
  '/admin/usuarios': typeof ShellAdminUsuariosRoute
  '/proyectos/$proyectoId': typeof ShellProyectosProyectoIdRoute
  '/revision/$versionId': typeof ShellRevisionVersionIdRoute
  '/admin/': typeof ShellAdminIndexRoute
  '/docente/': typeof ShellDocenteIndexRoute
  '/proyectos/': typeof ShellProyectosIndexRoute
  '/student/': typeof ShellStudentIndexRoute
  '/admin/materias/$materiaId': typeof ShellAdminMateriasMateriaIdRoute
  '/admin/usuarios/$usuarioId': typeof ShellAdminUsuariosUsuarioIdRoute
  '/admin/materias/': typeof ShellAdminMateriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof ShellCronogramaRoute
  '/notificaciones': typeof ShellNotificacionesRoute
  '/perfil': typeof ShellPerfilRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/reportes': typeof ShellAdminReportesRoute
  '/admin/usuarios': typeof ShellAdminUsuariosRoute
  '/proyectos/$proyectoId': typeof ShellProyectosProyectoIdRoute
  '/revision/$versionId': typeof ShellRevisionVersionIdRoute
  '/admin': typeof ShellAdminIndexRoute
  '/docente': typeof ShellDocenteIndexRoute
  '/proyectos': typeof ShellProyectosIndexRoute
  '/student': typeof ShellStudentIndexRoute
  '/admin/materias/$materiaId': typeof ShellAdminMateriasMateriaIdRoute
  '/admin/usuarios/$usuarioId': typeof ShellAdminUsuariosUsuarioIdRoute
  '/admin/materias': typeof ShellAdminMateriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/cronograma': typeof ShellCronogramaRoute
  '/_shell/notificaciones': typeof ShellNotificacionesRoute
  '/_shell/perfil': typeof ShellPerfilRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_shell/admin/reportes': typeof ShellAdminReportesRoute
  '/_shell/admin/usuarios': typeof ShellAdminUsuariosRoute
  '/_shell/proyectos/$proyectoId': typeof ShellProyectosProyectoIdRoute
  '/_shell/revision/$versionId': typeof ShellRevisionVersionIdRoute
  '/_shell/admin/': typeof ShellAdminIndexRoute
  '/_shell/docente/': typeof ShellDocenteIndexRoute
  '/_shell/proyectos/': typeof ShellProyectosIndexRoute
  '/_shell/student/': typeof ShellStudentIndexRoute
  '/_shell/admin/materias/$materiaId': typeof ShellAdminMateriasMateriaIdRoute
  '/_shell/admin/usuarios_/$usuarioId': typeof ShellAdminUsuariosUsuarioIdRoute
  '/_shell/admin/materias/': typeof ShellAdminMateriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cronograma'
    | '/notificaciones'
    | '/perfil'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/proyectos/$proyectoId'
    | '/revision/$versionId'
    | '/admin/'
    | '/docente/'
    | '/proyectos/'
    | '/student/'
    | '/admin/materias/$materiaId'
    | '/admin/usuarios/$usuarioId'
    | '/admin/materias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cronograma'
    | '/notificaciones'
    | '/perfil'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/proyectos/$proyectoId'
    | '/revision/$versionId'
    | '/admin'
    | '/docente'
    | '/proyectos'
    | '/student'
    | '/admin/materias/$materiaId'
    | '/admin/usuarios/$usuarioId'
    | '/admin/materias'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/cronograma'
    | '/_shell/notificaciones'
    | '/_shell/perfil'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_shell/admin/reportes'
    | '/_shell/admin/usuarios'
    | '/_shell/proyectos/$proyectoId'
    | '/_shell/revision/$versionId'
    | '/_shell/admin/'
    | '/_shell/docente/'
    | '/_shell/proyectos/'
    | '/_shell/student/'
    | '/_shell/admin/materias/$materiaId'
    | '/_shell/admin/usuarios_/$usuarioId'
    | '/_shell/admin/materias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/perfil': {
      id: '/_shell/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof ShellPerfilRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notificaciones': {
      id: '/_shell/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof ShellNotificacionesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cronograma': {
      id: '/_shell/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof ShellCronogramaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/student/': {
      id: '/_shell/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof ShellStudentIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/proyectos/': {
      id: '/_shell/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ShellProyectosIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docente/': {
      id: '/_shell/docente/'
      path: '/docente'
      fullPath: '/docente/'
      preLoaderRoute: typeof ShellDocenteIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/': {
      id: '/_shell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ShellAdminIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/revision/$versionId': {
      id: '/_shell/revision/$versionId'
      path: '/revision/$versionId'
      fullPath: '/revision/$versionId'
      preLoaderRoute: typeof ShellRevisionVersionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/proyectos/$proyectoId': {
      id: '/_shell/proyectos/$proyectoId'
      path: '/proyectos/$proyectoId'
      fullPath: '/proyectos/$proyectoId'
      preLoaderRoute: typeof ShellProyectosProyectoIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/usuarios': {
      id: '/_shell/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof ShellAdminUsuariosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/reportes': {
      id: '/_shell/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof ShellAdminReportesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/materias/': {
      id: '/_shell/admin/materias/'
      path: '/admin/materias'
      fullPath: '/admin/materias/'
      preLoaderRoute: typeof ShellAdminMateriasIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/usuarios_/$usuarioId': {
      id: '/_shell/admin/usuarios_/$usuarioId'
      path: '/admin/usuarios/$usuarioId'
      fullPath: '/admin/usuarios/$usuarioId'
      preLoaderRoute: typeof ShellAdminUsuariosUsuarioIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/materias/$materiaId': {
      id: '/_shell/admin/materias/$materiaId'
      path: '/admin/materias/$materiaId'
      fullPath: '/admin/materias/$materiaId'
      preLoaderRoute: typeof ShellAdminMateriasMateriaIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCronogramaRoute: typeof ShellCronogramaRoute
  ShellNotificacionesRoute: typeof ShellNotificacionesRoute
  ShellPerfilRoute: typeof ShellPerfilRoute
  ShellAdminReportesRoute: typeof ShellAdminReportesRoute
  ShellAdminUsuariosRoute: typeof ShellAdminUsuariosRoute
  ShellProyectosProyectoIdRoute: typeof ShellProyectosProyectoIdRoute
  ShellRevisionVersionIdRoute: typeof ShellRevisionVersionIdRoute
  ShellAdminIndexRoute: typeof ShellAdminIndexRoute
  ShellDocenteIndexRoute: typeof ShellDocenteIndexRoute
  ShellProyectosIndexRoute: typeof ShellProyectosIndexRoute
  ShellStudentIndexRoute: typeof ShellStudentIndexRoute
  ShellAdminMateriasMateriaIdRoute: typeof ShellAdminMateriasMateriaIdRoute
  ShellAdminUsuariosUsuarioIdRoute: typeof ShellAdminUsuariosUsuarioIdRoute
  ShellAdminMateriasIndexRoute: typeof ShellAdminMateriasIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCronogramaRoute: ShellCronogramaRoute,
  ShellNotificacionesRoute: ShellNotificacionesRoute,
  ShellPerfilRoute: ShellPerfilRoute,
  ShellAdminReportesRoute: ShellAdminReportesRoute,
  ShellAdminUsuariosRoute: ShellAdminUsuariosRoute,
  ShellProyectosProyectoIdRoute: ShellProyectosProyectoIdRoute,
  ShellRevisionVersionIdRoute: ShellRevisionVersionIdRoute,
  ShellAdminIndexRoute: ShellAdminIndexRoute,
  ShellDocenteIndexRoute: ShellDocenteIndexRoute,
  ShellProyectosIndexRoute: ShellProyectosIndexRoute,
  ShellStudentIndexRoute: ShellStudentIndexRoute,
  ShellAdminMateriasMateriaIdRoute: ShellAdminMateriasMateriaIdRoute,
  ShellAdminUsuariosUsuarioIdRoute: ShellAdminUsuariosUsuarioIdRoute,
  ShellAdminMateriasIndexRoute: ShellAdminMateriasIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
